export const URL = `http://localhost:8082`
export const CREATE_PAGE_ID=2
export const HOME_PAGE_ID=1
export const RESOURCES_PAGE_ID = 3
export const HISTORY_PAGE_ID = 4
export const emptySearch = ""
export const emptyType = ""
export const defaultStratingPage = 0
export const defaultResourceSize = 7